# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/projects/dinosauria

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/projects/dinosauria

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/projects/dinosauria/CMakeFiles /root/projects/dinosauria/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/projects/dinosauria/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/bconverter

# Build rule for target.
bin/bconverter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/bconverter
.PHONY : bin/bconverter

# fast build rule for target.
bin/bconverter/fast:
	$(MAKE) -f CMakeFiles/bin/bconverter.dir/build.make CMakeFiles/bin/bconverter.dir/build
.PHONY : bin/bconverter/fast

#=============================================================================
# Target rules for targets named bin/converter

# Build rule for target.
bin/converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/converter
.PHONY : bin/converter

# fast build rule for target.
bin/converter/fast:
	$(MAKE) -f CMakeFiles/bin/converter.dir/build.make CMakeFiles/bin/converter.dir/build
.PHONY : bin/converter/fast

#=============================================================================
# Target rules for targets named bin/dinosauria

# Build rule for target.
bin/dinosauria: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/dinosauria
.PHONY : bin/dinosauria

# fast build rule for target.
bin/dinosauria/fast:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/build
.PHONY : bin/dinosauria/fast

converters/bconverter.o: converters/bconverter.cpp.o
.PHONY : converters/bconverter.o

# target to build an object file
converters/bconverter.cpp.o:
	$(MAKE) -f CMakeFiles/bin/bconverter.dir/build.make CMakeFiles/bin/bconverter.dir/converters/bconverter.cpp.o
.PHONY : converters/bconverter.cpp.o

converters/bconverter.i: converters/bconverter.cpp.i
.PHONY : converters/bconverter.i

# target to preprocess a source file
converters/bconverter.cpp.i:
	$(MAKE) -f CMakeFiles/bin/bconverter.dir/build.make CMakeFiles/bin/bconverter.dir/converters/bconverter.cpp.i
.PHONY : converters/bconverter.cpp.i

converters/bconverter.s: converters/bconverter.cpp.s
.PHONY : converters/bconverter.s

# target to generate assembly for a file
converters/bconverter.cpp.s:
	$(MAKE) -f CMakeFiles/bin/bconverter.dir/build.make CMakeFiles/bin/bconverter.dir/converters/bconverter.cpp.s
.PHONY : converters/bconverter.cpp.s

converters/converter.o: converters/converter.cpp.o
.PHONY : converters/converter.o

# target to build an object file
converters/converter.cpp.o:
	$(MAKE) -f CMakeFiles/bin/converter.dir/build.make CMakeFiles/bin/converter.dir/converters/converter.cpp.o
.PHONY : converters/converter.cpp.o

converters/converter.i: converters/converter.cpp.i
.PHONY : converters/converter.i

# target to preprocess a source file
converters/converter.cpp.i:
	$(MAKE) -f CMakeFiles/bin/converter.dir/build.make CMakeFiles/bin/converter.dir/converters/converter.cpp.i
.PHONY : converters/converter.cpp.i

converters/converter.s: converters/converter.cpp.s
.PHONY : converters/converter.s

# target to generate assembly for a file
converters/converter.cpp.s:
	$(MAKE) -f CMakeFiles/bin/converter.dir/build.make CMakeFiles/bin/converter.dir/converters/converter.cpp.s
.PHONY : converters/converter.cpp.s

src/dinosauria.o: src/dinosauria.cpp.o
.PHONY : src/dinosauria.o

# target to build an object file
src/dinosauria.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/dinosauria.cpp.o
.PHONY : src/dinosauria.cpp.o

src/dinosauria.i: src/dinosauria.cpp.i
.PHONY : src/dinosauria.i

# target to preprocess a source file
src/dinosauria.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/dinosauria.cpp.i
.PHONY : src/dinosauria.cpp.i

src/dinosauria.s: src/dinosauria.cpp.s
.PHONY : src/dinosauria.s

# target to generate assembly for a file
src/dinosauria.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/dinosauria.cpp.s
.PHONY : src/dinosauria.cpp.s

src/game/dinosaur.o: src/game/dinosaur.cpp.o
.PHONY : src/game/dinosaur.o

# target to build an object file
src/game/dinosaur.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/dinosaur.cpp.o
.PHONY : src/game/dinosaur.cpp.o

src/game/dinosaur.i: src/game/dinosaur.cpp.i
.PHONY : src/game/dinosaur.i

# target to preprocess a source file
src/game/dinosaur.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/dinosaur.cpp.i
.PHONY : src/game/dinosaur.cpp.i

src/game/dinosaur.s: src/game/dinosaur.cpp.s
.PHONY : src/game/dinosaur.s

# target to generate assembly for a file
src/game/dinosaur.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/dinosaur.cpp.s
.PHONY : src/game/dinosaur.cpp.s

src/game/game.o: src/game/game.cpp.o
.PHONY : src/game/game.o

# target to build an object file
src/game/game.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/game.cpp.o
.PHONY : src/game/game.cpp.o

src/game/game.i: src/game/game.cpp.i
.PHONY : src/game/game.i

# target to preprocess a source file
src/game/game.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/game.cpp.i
.PHONY : src/game/game.cpp.i

src/game/game.s: src/game/game.cpp.s
.PHONY : src/game/game.s

# target to generate assembly for a file
src/game/game.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/game.cpp.s
.PHONY : src/game/game.cpp.s

src/game/landscape.o: src/game/landscape.cpp.o
.PHONY : src/game/landscape.o

# target to build an object file
src/game/landscape.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/landscape.cpp.o
.PHONY : src/game/landscape.cpp.o

src/game/landscape.i: src/game/landscape.cpp.i
.PHONY : src/game/landscape.i

# target to preprocess a source file
src/game/landscape.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/landscape.cpp.i
.PHONY : src/game/landscape.cpp.i

src/game/landscape.s: src/game/landscape.cpp.s
.PHONY : src/game/landscape.s

# target to generate assembly for a file
src/game/landscape.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/landscape.cpp.s
.PHONY : src/game/landscape.cpp.s

src/game/water.o: src/game/water.cpp.o
.PHONY : src/game/water.o

# target to build an object file
src/game/water.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/water.cpp.o
.PHONY : src/game/water.cpp.o

src/game/water.i: src/game/water.cpp.i
.PHONY : src/game/water.i

# target to preprocess a source file
src/game/water.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/water.cpp.i
.PHONY : src/game/water.cpp.i

src/game/water.s: src/game/water.cpp.s
.PHONY : src/game/water.s

# target to generate assembly for a file
src/game/water.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/game/water.cpp.s
.PHONY : src/game/water.cpp.s

src/graphics/background.o: src/graphics/background.cpp.o
.PHONY : src/graphics/background.o

# target to build an object file
src/graphics/background.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/background.cpp.o
.PHONY : src/graphics/background.cpp.o

src/graphics/background.i: src/graphics/background.cpp.i
.PHONY : src/graphics/background.i

# target to preprocess a source file
src/graphics/background.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/background.cpp.i
.PHONY : src/graphics/background.cpp.i

src/graphics/background.s: src/graphics/background.cpp.s
.PHONY : src/graphics/background.s

# target to generate assembly for a file
src/graphics/background.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/background.cpp.s
.PHONY : src/graphics/background.cpp.s

src/graphics/base.o: src/graphics/base.cpp.o
.PHONY : src/graphics/base.o

# target to build an object file
src/graphics/base.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/base.cpp.o
.PHONY : src/graphics/base.cpp.o

src/graphics/base.i: src/graphics/base.cpp.i
.PHONY : src/graphics/base.i

# target to preprocess a source file
src/graphics/base.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/base.cpp.i
.PHONY : src/graphics/base.cpp.i

src/graphics/base.s: src/graphics/base.cpp.s
.PHONY : src/graphics/base.s

# target to generate assembly for a file
src/graphics/base.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/base.cpp.s
.PHONY : src/graphics/base.cpp.s

src/graphics/bmesh.o: src/graphics/bmesh.cpp.o
.PHONY : src/graphics/bmesh.o

# target to build an object file
src/graphics/bmesh.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/bmesh.cpp.o
.PHONY : src/graphics/bmesh.cpp.o

src/graphics/bmesh.i: src/graphics/bmesh.cpp.i
.PHONY : src/graphics/bmesh.i

# target to preprocess a source file
src/graphics/bmesh.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/bmesh.cpp.i
.PHONY : src/graphics/bmesh.cpp.i

src/graphics/bmesh.s: src/graphics/bmesh.cpp.s
.PHONY : src/graphics/bmesh.s

# target to generate assembly for a file
src/graphics/bmesh.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/bmesh.cpp.s
.PHONY : src/graphics/bmesh.cpp.s

src/graphics/buffer.o: src/graphics/buffer.cpp.o
.PHONY : src/graphics/buffer.o

# target to build an object file
src/graphics/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/buffer.cpp.o
.PHONY : src/graphics/buffer.cpp.o

src/graphics/buffer.i: src/graphics/buffer.cpp.i
.PHONY : src/graphics/buffer.i

# target to preprocess a source file
src/graphics/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/buffer.cpp.i
.PHONY : src/graphics/buffer.cpp.i

src/graphics/buffer.s: src/graphics/buffer.cpp.s
.PHONY : src/graphics/buffer.s

# target to generate assembly for a file
src/graphics/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/buffer.cpp.s
.PHONY : src/graphics/buffer.cpp.s

src/graphics/camera.o: src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.o

# target to build an object file
src/graphics/camera.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.cpp.o

src/graphics/camera.i: src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.cpp.i

src/graphics/camera.s: src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.cpp.s

src/graphics/fbo.o: src/graphics/fbo.cpp.o
.PHONY : src/graphics/fbo.o

# target to build an object file
src/graphics/fbo.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/fbo.cpp.o
.PHONY : src/graphics/fbo.cpp.o

src/graphics/fbo.i: src/graphics/fbo.cpp.i
.PHONY : src/graphics/fbo.i

# target to preprocess a source file
src/graphics/fbo.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/fbo.cpp.i
.PHONY : src/graphics/fbo.cpp.i

src/graphics/fbo.s: src/graphics/fbo.cpp.s
.PHONY : src/graphics/fbo.s

# target to generate assembly for a file
src/graphics/fbo.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/fbo.cpp.s
.PHONY : src/graphics/fbo.cpp.s

src/graphics/glsl.o: src/graphics/glsl.cpp.o
.PHONY : src/graphics/glsl.o

# target to build an object file
src/graphics/glsl.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl.cpp.o
.PHONY : src/graphics/glsl.cpp.o

src/graphics/glsl.i: src/graphics/glsl.cpp.i
.PHONY : src/graphics/glsl.i

# target to preprocess a source file
src/graphics/glsl.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl.cpp.i
.PHONY : src/graphics/glsl.cpp.i

src/graphics/glsl.s: src/graphics/glsl.cpp.s
.PHONY : src/graphics/glsl.s

# target to generate assembly for a file
src/graphics/glsl.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl.cpp.s
.PHONY : src/graphics/glsl.cpp.s

src/graphics/glsl_unif.o: src/graphics/glsl_unif.cpp.o
.PHONY : src/graphics/glsl_unif.o

# target to build an object file
src/graphics/glsl_unif.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl_unif.cpp.o
.PHONY : src/graphics/glsl_unif.cpp.o

src/graphics/glsl_unif.i: src/graphics/glsl_unif.cpp.i
.PHONY : src/graphics/glsl_unif.i

# target to preprocess a source file
src/graphics/glsl_unif.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl_unif.cpp.i
.PHONY : src/graphics/glsl_unif.cpp.i

src/graphics/glsl_unif.s: src/graphics/glsl_unif.cpp.s
.PHONY : src/graphics/glsl_unif.s

# target to generate assembly for a file
src/graphics/glsl_unif.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/glsl_unif.cpp.s
.PHONY : src/graphics/glsl_unif.cpp.s

src/graphics/ibo.o: src/graphics/ibo.cpp.o
.PHONY : src/graphics/ibo.o

# target to build an object file
src/graphics/ibo.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/ibo.cpp.o
.PHONY : src/graphics/ibo.cpp.o

src/graphics/ibo.i: src/graphics/ibo.cpp.i
.PHONY : src/graphics/ibo.i

# target to preprocess a source file
src/graphics/ibo.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/ibo.cpp.i
.PHONY : src/graphics/ibo.cpp.i

src/graphics/ibo.s: src/graphics/ibo.cpp.s
.PHONY : src/graphics/ibo.s

# target to generate assembly for a file
src/graphics/ibo.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/ibo.cpp.s
.PHONY : src/graphics/ibo.cpp.s

src/graphics/material.o: src/graphics/material.cpp.o
.PHONY : src/graphics/material.o

# target to build an object file
src/graphics/material.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/material.cpp.o
.PHONY : src/graphics/material.cpp.o

src/graphics/material.i: src/graphics/material.cpp.i
.PHONY : src/graphics/material.i

# target to preprocess a source file
src/graphics/material.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/material.cpp.i
.PHONY : src/graphics/material.cpp.i

src/graphics/material.s: src/graphics/material.cpp.s
.PHONY : src/graphics/material.s

# target to generate assembly for a file
src/graphics/material.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/material.cpp.s
.PHONY : src/graphics/material.cpp.s

src/graphics/mesh.o: src/graphics/mesh.cpp.o
.PHONY : src/graphics/mesh.o

# target to build an object file
src/graphics/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/mesh.cpp.o
.PHONY : src/graphics/mesh.cpp.o

src/graphics/mesh.i: src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.i

# target to preprocess a source file
src/graphics/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.cpp.i

src/graphics/mesh.s: src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.s

# target to generate assembly for a file
src/graphics/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.cpp.s

src/graphics/post.o: src/graphics/post.cpp.o
.PHONY : src/graphics/post.o

# target to build an object file
src/graphics/post.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/post.cpp.o
.PHONY : src/graphics/post.cpp.o

src/graphics/post.i: src/graphics/post.cpp.i
.PHONY : src/graphics/post.i

# target to preprocess a source file
src/graphics/post.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/post.cpp.i
.PHONY : src/graphics/post.cpp.i

src/graphics/post.s: src/graphics/post.cpp.s
.PHONY : src/graphics/post.s

# target to generate assembly for a file
src/graphics/post.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/post.cpp.s
.PHONY : src/graphics/post.cpp.s

src/graphics/rendObj.o: src/graphics/rendObj.cpp.o
.PHONY : src/graphics/rendObj.o

# target to build an object file
src/graphics/rendObj.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/rendObj.cpp.o
.PHONY : src/graphics/rendObj.cpp.o

src/graphics/rendObj.i: src/graphics/rendObj.cpp.i
.PHONY : src/graphics/rendObj.i

# target to preprocess a source file
src/graphics/rendObj.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/rendObj.cpp.i
.PHONY : src/graphics/rendObj.cpp.i

src/graphics/rendObj.s: src/graphics/rendObj.cpp.s
.PHONY : src/graphics/rendObj.s

# target to generate assembly for a file
src/graphics/rendObj.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/rendObj.cpp.s
.PHONY : src/graphics/rendObj.cpp.s

src/graphics/sky.o: src/graphics/sky.cpp.o
.PHONY : src/graphics/sky.o

# target to build an object file
src/graphics/sky.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/sky.cpp.o
.PHONY : src/graphics/sky.cpp.o

src/graphics/sky.i: src/graphics/sky.cpp.i
.PHONY : src/graphics/sky.i

# target to preprocess a source file
src/graphics/sky.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/sky.cpp.i
.PHONY : src/graphics/sky.cpp.i

src/graphics/sky.s: src/graphics/sky.cpp.s
.PHONY : src/graphics/sky.s

# target to generate assembly for a file
src/graphics/sky.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/sky.cpp.s
.PHONY : src/graphics/sky.cpp.s

src/graphics/text.o: src/graphics/text.cpp.o
.PHONY : src/graphics/text.o

# target to build an object file
src/graphics/text.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/text.cpp.o
.PHONY : src/graphics/text.cpp.o

src/graphics/text.i: src/graphics/text.cpp.i
.PHONY : src/graphics/text.i

# target to preprocess a source file
src/graphics/text.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/text.cpp.i
.PHONY : src/graphics/text.cpp.i

src/graphics/text.s: src/graphics/text.cpp.s
.PHONY : src/graphics/text.s

# target to generate assembly for a file
src/graphics/text.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/text.cpp.s
.PHONY : src/graphics/text.cpp.s

src/graphics/texture.o: src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.o

# target to build an object file
src/graphics/texture.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.cpp.o

src/graphics/texture.i: src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/world.o: src/graphics/world.cpp.o
.PHONY : src/graphics/world.o

# target to build an object file
src/graphics/world.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/world.cpp.o
.PHONY : src/graphics/world.cpp.o

src/graphics/world.i: src/graphics/world.cpp.i
.PHONY : src/graphics/world.i

# target to preprocess a source file
src/graphics/world.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/world.cpp.i
.PHONY : src/graphics/world.cpp.i

src/graphics/world.s: src/graphics/world.cpp.s
.PHONY : src/graphics/world.s

# target to generate assembly for a file
src/graphics/world.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/graphics/world.cpp.s
.PHONY : src/graphics/world.cpp.s

src/gui/button.o: src/gui/button.cpp.o
.PHONY : src/gui/button.o

# target to build an object file
src/gui/button.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/button.cpp.o
.PHONY : src/gui/button.cpp.o

src/gui/button.i: src/gui/button.cpp.i
.PHONY : src/gui/button.i

# target to preprocess a source file
src/gui/button.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/button.cpp.i
.PHONY : src/gui/button.cpp.i

src/gui/button.s: src/gui/button.cpp.s
.PHONY : src/gui/button.s

# target to generate assembly for a file
src/gui/button.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/button.cpp.s
.PHONY : src/gui/button.cpp.s

src/gui/fonts.o: src/gui/fonts.cpp.o
.PHONY : src/gui/fonts.o

# target to build an object file
src/gui/fonts.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/fonts.cpp.o
.PHONY : src/gui/fonts.cpp.o

src/gui/fonts.i: src/gui/fonts.cpp.i
.PHONY : src/gui/fonts.i

# target to preprocess a source file
src/gui/fonts.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/fonts.cpp.i
.PHONY : src/gui/fonts.cpp.i

src/gui/fonts.s: src/gui/fonts.cpp.s
.PHONY : src/gui/fonts.s

# target to generate assembly for a file
src/gui/fonts.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/fonts.cpp.s
.PHONY : src/gui/fonts.cpp.s

src/gui/frame.o: src/gui/frame.cpp.o
.PHONY : src/gui/frame.o

# target to build an object file
src/gui/frame.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/frame.cpp.o
.PHONY : src/gui/frame.cpp.o

src/gui/frame.i: src/gui/frame.cpp.i
.PHONY : src/gui/frame.i

# target to preprocess a source file
src/gui/frame.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/frame.cpp.i
.PHONY : src/gui/frame.cpp.i

src/gui/frame.s: src/gui/frame.cpp.s
.PHONY : src/gui/frame.s

# target to generate assembly for a file
src/gui/frame.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/frame.cpp.s
.PHONY : src/gui/frame.cpp.s

src/gui/guiManage.o: src/gui/guiManage.cpp.o
.PHONY : src/gui/guiManage.o

# target to build an object file
src/gui/guiManage.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/guiManage.cpp.o
.PHONY : src/gui/guiManage.cpp.o

src/gui/guiManage.i: src/gui/guiManage.cpp.i
.PHONY : src/gui/guiManage.i

# target to preprocess a source file
src/gui/guiManage.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/guiManage.cpp.i
.PHONY : src/gui/guiManage.cpp.i

src/gui/guiManage.s: src/gui/guiManage.cpp.s
.PHONY : src/gui/guiManage.s

# target to generate assembly for a file
src/gui/guiManage.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/guiManage.cpp.s
.PHONY : src/gui/guiManage.cpp.s

src/gui/pbar.o: src/gui/pbar.cpp.o
.PHONY : src/gui/pbar.o

# target to build an object file
src/gui/pbar.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/pbar.cpp.o
.PHONY : src/gui/pbar.cpp.o

src/gui/pbar.i: src/gui/pbar.cpp.i
.PHONY : src/gui/pbar.i

# target to preprocess a source file
src/gui/pbar.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/pbar.cpp.i
.PHONY : src/gui/pbar.cpp.i

src/gui/pbar.s: src/gui/pbar.cpp.s
.PHONY : src/gui/pbar.s

# target to generate assembly for a file
src/gui/pbar.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/pbar.cpp.s
.PHONY : src/gui/pbar.cpp.s

src/gui/text.o: src/gui/text.cpp.o
.PHONY : src/gui/text.o

# target to build an object file
src/gui/text.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/text.cpp.o
.PHONY : src/gui/text.cpp.o

src/gui/text.i: src/gui/text.cpp.i
.PHONY : src/gui/text.i

# target to preprocess a source file
src/gui/text.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/text.cpp.i
.PHONY : src/gui/text.cpp.i

src/gui/text.s: src/gui/text.cpp.s
.PHONY : src/gui/text.s

# target to generate assembly for a file
src/gui/text.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/gui/text.cpp.s
.PHONY : src/gui/text.cpp.s

src/pgen/fbm.o: src/pgen/fbm.cpp.o
.PHONY : src/pgen/fbm.o

# target to build an object file
src/pgen/fbm.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/fbm.cpp.o
.PHONY : src/pgen/fbm.cpp.o

src/pgen/fbm.i: src/pgen/fbm.cpp.i
.PHONY : src/pgen/fbm.i

# target to preprocess a source file
src/pgen/fbm.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/fbm.cpp.i
.PHONY : src/pgen/fbm.cpp.i

src/pgen/fbm.s: src/pgen/fbm.cpp.s
.PHONY : src/pgen/fbm.s

# target to generate assembly for a file
src/pgen/fbm.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/fbm.cpp.s
.PHONY : src/pgen/fbm.cpp.s

src/pgen/terrain.o: src/pgen/terrain.cpp.o
.PHONY : src/pgen/terrain.o

# target to build an object file
src/pgen/terrain.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/terrain.cpp.o
.PHONY : src/pgen/terrain.cpp.o

src/pgen/terrain.i: src/pgen/terrain.cpp.i
.PHONY : src/pgen/terrain.i

# target to preprocess a source file
src/pgen/terrain.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/terrain.cpp.i
.PHONY : src/pgen/terrain.cpp.i

src/pgen/terrain.s: src/pgen/terrain.cpp.s
.PHONY : src/pgen/terrain.s

# target to generate assembly for a file
src/pgen/terrain.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/terrain.cpp.s
.PHONY : src/pgen/terrain.cpp.s

src/pgen/water.o: src/pgen/water.cpp.o
.PHONY : src/pgen/water.o

# target to build an object file
src/pgen/water.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/water.cpp.o
.PHONY : src/pgen/water.cpp.o

src/pgen/water.i: src/pgen/water.cpp.i
.PHONY : src/pgen/water.i

# target to preprocess a source file
src/pgen/water.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/water.cpp.i
.PHONY : src/pgen/water.cpp.i

src/pgen/water.s: src/pgen/water.cpp.s
.PHONY : src/pgen/water.s

# target to generate assembly for a file
src/pgen/water.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/pgen/water.cpp.s
.PHONY : src/pgen/water.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/bin/dinosauria.dir/build.make CMakeFiles/bin/dinosauria.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/bconverter"
	@echo "... bin/converter"
	@echo "... bin/dinosauria"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... converters/bconverter.o"
	@echo "... converters/bconverter.i"
	@echo "... converters/bconverter.s"
	@echo "... converters/converter.o"
	@echo "... converters/converter.i"
	@echo "... converters/converter.s"
	@echo "... src/dinosauria.o"
	@echo "... src/dinosauria.i"
	@echo "... src/dinosauria.s"
	@echo "... src/game/dinosaur.o"
	@echo "... src/game/dinosaur.i"
	@echo "... src/game/dinosaur.s"
	@echo "... src/game/game.o"
	@echo "... src/game/game.i"
	@echo "... src/game/game.s"
	@echo "... src/game/landscape.o"
	@echo "... src/game/landscape.i"
	@echo "... src/game/landscape.s"
	@echo "... src/game/water.o"
	@echo "... src/game/water.i"
	@echo "... src/game/water.s"
	@echo "... src/graphics/background.o"
	@echo "... src/graphics/background.i"
	@echo "... src/graphics/background.s"
	@echo "... src/graphics/base.o"
	@echo "... src/graphics/base.i"
	@echo "... src/graphics/base.s"
	@echo "... src/graphics/bmesh.o"
	@echo "... src/graphics/bmesh.i"
	@echo "... src/graphics/bmesh.s"
	@echo "... src/graphics/buffer.o"
	@echo "... src/graphics/buffer.i"
	@echo "... src/graphics/buffer.s"
	@echo "... src/graphics/camera.o"
	@echo "... src/graphics/camera.i"
	@echo "... src/graphics/camera.s"
	@echo "... src/graphics/fbo.o"
	@echo "... src/graphics/fbo.i"
	@echo "... src/graphics/fbo.s"
	@echo "... src/graphics/glsl.o"
	@echo "... src/graphics/glsl.i"
	@echo "... src/graphics/glsl.s"
	@echo "... src/graphics/glsl_unif.o"
	@echo "... src/graphics/glsl_unif.i"
	@echo "... src/graphics/glsl_unif.s"
	@echo "... src/graphics/ibo.o"
	@echo "... src/graphics/ibo.i"
	@echo "... src/graphics/ibo.s"
	@echo "... src/graphics/material.o"
	@echo "... src/graphics/material.i"
	@echo "... src/graphics/material.s"
	@echo "... src/graphics/mesh.o"
	@echo "... src/graphics/mesh.i"
	@echo "... src/graphics/mesh.s"
	@echo "... src/graphics/post.o"
	@echo "... src/graphics/post.i"
	@echo "... src/graphics/post.s"
	@echo "... src/graphics/rendObj.o"
	@echo "... src/graphics/rendObj.i"
	@echo "... src/graphics/rendObj.s"
	@echo "... src/graphics/sky.o"
	@echo "... src/graphics/sky.i"
	@echo "... src/graphics/sky.s"
	@echo "... src/graphics/text.o"
	@echo "... src/graphics/text.i"
	@echo "... src/graphics/text.s"
	@echo "... src/graphics/texture.o"
	@echo "... src/graphics/texture.i"
	@echo "... src/graphics/texture.s"
	@echo "... src/graphics/world.o"
	@echo "... src/graphics/world.i"
	@echo "... src/graphics/world.s"
	@echo "... src/gui/button.o"
	@echo "... src/gui/button.i"
	@echo "... src/gui/button.s"
	@echo "... src/gui/fonts.o"
	@echo "... src/gui/fonts.i"
	@echo "... src/gui/fonts.s"
	@echo "... src/gui/frame.o"
	@echo "... src/gui/frame.i"
	@echo "... src/gui/frame.s"
	@echo "... src/gui/guiManage.o"
	@echo "... src/gui/guiManage.i"
	@echo "... src/gui/guiManage.s"
	@echo "... src/gui/pbar.o"
	@echo "... src/gui/pbar.i"
	@echo "... src/gui/pbar.s"
	@echo "... src/gui/text.o"
	@echo "... src/gui/text.i"
	@echo "... src/gui/text.s"
	@echo "... src/pgen/fbm.o"
	@echo "... src/pgen/fbm.i"
	@echo "... src/pgen/fbm.s"
	@echo "... src/pgen/terrain.o"
	@echo "... src/pgen/terrain.i"
	@echo "... src/pgen/terrain.s"
	@echo "... src/pgen/water.o"
	@echo "... src/pgen/water.i"
	@echo "... src/pgen/water.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

