set(SRC_FILES src/util.cpp
	      src/gui/guiManage.cpp
	      src/gui/button.cpp
	      src/gui/text.cpp
	      src/gui/frame.cpp
	      src/gui/pbar.cpp
	      src/gui/fonts.cpp
	      src/pgen/fbm.cpp
	      src/pgen/terrain.cpp
	      src/pgen/water.cpp
	      src/graphics/ibo.cpp
	      src/graphics/fbo.cpp
	      src/graphics/bmesh.cpp
	      src/graphics/glsl.cpp
	      src/graphics/mesh.cpp
	      src/graphics/camera.cpp
	      src/graphics/texture.cpp
	      src/graphics/background.cpp
	      src/graphics/glsl_unif.cpp
	      src/graphics/buffer.cpp
	      src/graphics/post.cpp
	      src/graphics/rendObj.cpp
	      src/graphics/text.cpp
	      src/graphics/base.cpp
	      src/graphics/world.cpp
	      src/graphics/material.cpp
	      src/graphics/sky.cpp
	      src/game/landscape.cpp
	      src/game/game.cpp
	      src/game/dinosaur.cpp
	      src/game/water.cpp
	      src/game/render_system.cpp
	      src/engine/entity.cpp
	      src/engine/component.cpp
	      src/engine/engine.cpp)